with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  github.com/es-debug/backend-academy-2024-go-template/internal/infrastructure/handlers:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      Scrapper:
      Bot:
  github.com/es-debug/backend-academy-2024-go-template/internal/application:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      Database:
      BotClient:
      ScrapperClient:
      TelegramClient: