with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  LinkTracker/internal/infrastructure/httpapi/links:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
  #      LinkDeleter:
  #      LinkGetter:
  #      LinkAdder:
  LinkTracker/internal/infrastructure/httpapi/tgchat:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
  #      UserDeleter:
  #      UserAdder:
  LinkTracker/internal/infrastructure/httpapi/updates:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
  #      MessageSender:
  LinkTracker/internal/application:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
  #      UserRepo:
  #      LinkRepo:
  #      BotClient:
  #      ScrapperClient:
  #      TelegramClient:
  #      LinkSourceHandler:
  LinkTracker/internal/infrastructure/clients:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
#      Bot:



