scrapper:
  address: ":8080"
  bot_baseurl: "http://localhost:8081"
  scrap_interval: 5m
  read_timeout: 5s
  write_timeout: 15s
  bot_client_timeout: 5s
  logger_path: "./logs/scrapper_logs.txt"

bot:
  tg_token: "your_tg_token"
  address: ":8081"
  scrapper_baseurl: "http://localhost:8080"
  read_timeout: 5s
  write_timeout: 15s
  scrapper_client_timeout: 5s
  logger_path: "./logs/bot_logs.txt"
