# Этап сборки
FROM golang:1.23-alpine AS builder
WORKDIR /build

# Зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем всё и билдим
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o bot ./cmd/bot

# Финальный минимальный образ
FROM alpine:latest AS runtime
RUN apk --no-cache add ca-certificates

COPY --from=builder /build/bot /bin/bot
CMD ["/bin/bot"]
