services:
  postgres:
    image: postgres
    container_name: scrapper-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 0.4s
      timeout: 0.4s
      retries: 10

  migrate:
    container_name: migrations
    image: migrate/migrate
    command:
      - --path=/migrations
      - --database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge


#  liquibase-migrations:
#    container_name: migrationsLiquid
#    image: liquibase/liquibase
#    depends_on:
#      - postgres
#    command:
#      - --searchPath=/changesets
#      - --changelog-file=master_liquibase.xml
#      - --driver=org.postgresql.Driver
#      - --url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
#      - --username=${POSTGRES_USER}
#      - --password=${POSTGRES_PASSWORD}
#      - update
#    volumes:
#      - ./migrations:/changesets
#    networks:
#      - backend





