CREATE TABLE "tracks"
(
    "tg_id"   BIGINT  NOT NULL,
    "url_id"  INTEGER NOT NULL,
    "filters" TEXT ARRAY,
    "tags"    TEXT ARRAY,
    PRIMARY KEY ("tg_id", "url_id")
);

CREATE TABLE "users"
(
    "tg_id" BIGINT NOT NULL,
    PRIMARY KEY ("tg_id")
);

CREATE TABLE "states"
(
    "tg_id"   BIGINT  NOT NULL,
    "state"   INTEGER NOT NULL,
    "url"     TEXT,
    "filters" TEXT ARRAY,
    "tags"    TEXT ARRAY,
    PRIMARY KEY ("tg_id")
);


CREATE TABLE "urls"
(
    "id"          INTEGER   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "url"         TEXT      NOT NULL UNIQUE,
    "last_update" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "tracks"
    ADD FOREIGN KEY ("url_id") REFERENCES "urls" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tracks"
    ADD FOREIGN KEY ("tg_id") REFERENCES "users" ("tg_id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;