// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserDeleter is an autogenerated mock type for the UserDeleter type
type UserDeleter struct {
	mock.Mock
}

type UserDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserDeleter) EXPECT() *UserDeleter_Expecter {
	return &UserDeleter_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function with given fields: _a0
func (_m *UserDeleter) DeleteUser(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserDeleter_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserDeleter_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - _a0 int64
func (_e *UserDeleter_Expecter) DeleteUser(_a0 interface{}) *UserDeleter_DeleteUser_Call {
	return &UserDeleter_DeleteUser_Call{Call: _e.mock.On("DeleteUser", _a0)}
}

func (_c *UserDeleter_DeleteUser_Call) Run(run func(_a0 int64)) *UserDeleter_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *UserDeleter_DeleteUser_Call) Return(_a0 error) *UserDeleter_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserDeleter_DeleteUser_Call) RunAndReturn(run func(int64) error) *UserDeleter_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserDeleter creates a new instance of UserDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDeleter {
	mock := &UserDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
