// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LinkChecker is an autogenerated mock type for the LinkChecker type
type LinkChecker struct {
	mock.Mock
}

type LinkChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkChecker) EXPECT() *LinkChecker_Expecter {
	return &LinkChecker_Expecter{mock: &_m.Mock}
}

// Scrape provides a mock function with given fields: ctx
func (_m *LinkChecker) Scrape(ctx context.Context) {
	_m.Called(ctx)
}

// LinkChecker_Scrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scrape'
type LinkChecker_Scrape_Call struct {
	*mock.Call
}

// Scrape is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LinkChecker_Expecter) Scrape(ctx interface{}) *LinkChecker_Scrape_Call {
	return &LinkChecker_Scrape_Call{Call: _e.mock.On("Scrape", ctx)}
}

func (_c *LinkChecker_Scrape_Call) Run(run func(ctx context.Context)) *LinkChecker_Scrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LinkChecker_Scrape_Call) Return() *LinkChecker_Scrape_Call {
	_c.Call.Return()
	return _c
}

func (_c *LinkChecker_Scrape_Call) RunAndReturn(run func(context.Context)) *LinkChecker_Scrape_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkChecker creates a new instance of LinkChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkChecker {
	mock := &LinkChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
