// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	domain "LinkTracker/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

type Notifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifier) EXPECT() *Notifier_Expecter {
	return &Notifier_Expecter{mock: &_m.Mock}
}

// PostUpdates provides a mock function with given fields: ctx, link, tgID, description
func (_m *Notifier) PostUpdates(ctx context.Context, link *domain.Link, tgID []int64, description string) error {
	ret := _m.Called(ctx, link, tgID, description)

	if len(ret) == 0 {
		panic("no return value specified for PostUpdates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Link, []int64, string) error); ok {
		r0 = rf(ctx, link, tgID, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Notifier_PostUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUpdates'
type Notifier_PostUpdates_Call struct {
	*mock.Call
}

// PostUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
//   - tgID []int64
//   - description string
func (_e *Notifier_Expecter) PostUpdates(ctx interface{}, link interface{}, tgID interface{}, description interface{}) *Notifier_PostUpdates_Call {
	return &Notifier_PostUpdates_Call{Call: _e.mock.On("PostUpdates", ctx, link, tgID, description)}
}

func (_c *Notifier_PostUpdates_Call) Run(run func(ctx context.Context, link *domain.Link, tgID []int64, description string)) *Notifier_PostUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Link), args[2].([]int64), args[3].(string))
	})
	return _c
}

func (_c *Notifier_PostUpdates_Call) Return(_a0 error) *Notifier_PostUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notifier_PostUpdates_Call) RunAndReturn(run func(context.Context, *domain.Link, []int64, string) error) *Notifier_PostUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
