// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	domain "LinkTracker/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BotClient is an autogenerated mock type for the BotClient type
type BotClient struct {
	mock.Mock
}

type BotClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BotClient) EXPECT() *BotClient_Expecter {
	return &BotClient_Expecter{mock: &_m.Mock}
}

// PostUpdates provides a mock function with given fields: ctx, link, tgID, description
func (_m *BotClient) PostUpdates(ctx context.Context, link *domain.Link, tgID []int64, description string) error {
	ret := _m.Called(ctx, link, tgID, description)

	if len(ret) == 0 {
		panic("no return value specified for PostUpdates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Link, []int64, string) error); ok {
		r0 = rf(ctx, link, tgID, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BotClient_PostUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUpdates'
type BotClient_PostUpdates_Call struct {
	*mock.Call
}

// PostUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
//   - tgID []int64
//   - description string
func (_e *BotClient_Expecter) PostUpdates(ctx interface{}, link interface{}, tgID interface{}, description interface{}) *BotClient_PostUpdates_Call {
	return &BotClient_PostUpdates_Call{Call: _e.mock.On("PostUpdates", ctx, link, tgID, description)}
}

func (_c *BotClient_PostUpdates_Call) Run(run func(ctx context.Context, link *domain.Link, tgID []int64, description string)) *BotClient_PostUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Link), args[2].([]int64), args[3].(string))
	})
	return _c
}

func (_c *BotClient_PostUpdates_Call) Return(_a0 error) *BotClient_PostUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BotClient_PostUpdates_Call) RunAndReturn(run func(context.Context, *domain.Link, []int64, string) error) *BotClient_PostUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewBotClient creates a new instance of BotClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBotClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BotClient {
	mock := &BotClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
