// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Bot is an autogenerated mock type for the Bot type
type Bot struct {
	mock.Mock
}

type Bot_Expecter struct {
	mock *mock.Mock
}

func (_m *Bot) EXPECT() *Bot_Expecter {
	return &Bot_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: chatID, message
func (_m *Bot) SendMessage(chatID int64, message string) {
	_m.Called(chatID, message)
}

// Bot_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type Bot_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - chatID int64
//   - message string
func (_e *Bot_Expecter) SendMessage(chatID interface{}, message interface{}) *Bot_SendMessage_Call {
	return &Bot_SendMessage_Call{Call: _e.mock.On("SendMessage", chatID, message)}
}

func (_c *Bot_SendMessage_Call) Run(run func(chatID int64, message string)) *Bot_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *Bot_SendMessage_Call) Return() *Bot_SendMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bot_SendMessage_Call) RunAndReturn(run func(int64, string)) *Bot_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewBot creates a new instance of Bot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBot(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bot {
	mock := &Bot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
