// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StateDeleter is an autogenerated mock type for the StateDeleter type
type StateDeleter struct {
	mock.Mock
}

type StateDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *StateDeleter) EXPECT() *StateDeleter_Expecter {
	return &StateDeleter_Expecter{mock: &_m.Mock}
}

// DeleteState provides a mock function with given fields: ctx, tgID
func (_m *StateDeleter) DeleteState(ctx context.Context, tgID int64) error {
	ret := _m.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, tgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateDeleter_DeleteState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteState'
type StateDeleter_DeleteState_Call struct {
	*mock.Call
}

// DeleteState is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
func (_e *StateDeleter_Expecter) DeleteState(ctx interface{}, tgID interface{}) *StateDeleter_DeleteState_Call {
	return &StateDeleter_DeleteState_Call{Call: _e.mock.On("DeleteState", ctx, tgID)}
}

func (_c *StateDeleter_DeleteState_Call) Run(run func(ctx context.Context, tgID int64)) *StateDeleter_DeleteState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *StateDeleter_DeleteState_Call) Return(_a0 error) *StateDeleter_DeleteState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateDeleter_DeleteState_Call) RunAndReturn(run func(context.Context, int64) error) *StateDeleter_DeleteState_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateDeleter creates a new instance of StateDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateDeleter {
	mock := &StateDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
