// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	domain "LinkTracker/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StateUpdater is an autogenerated mock type for the StateUpdater type
type StateUpdater struct {
	mock.Mock
}

type StateUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *StateUpdater) EXPECT() *StateUpdater_Expecter {
	return &StateUpdater_Expecter{mock: &_m.Mock}
}

// UpdateState provides a mock function with given fields: ctx, tgID, state, link
func (_m *StateUpdater) UpdateState(ctx context.Context, tgID int64, state int, link *domain.Link) error {
	ret := _m.Called(ctx, tgID, state, link)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, *domain.Link) error); ok {
		r0 = rf(ctx, tgID, state, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateUpdater_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type StateUpdater_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
//   - state int
//   - link *domain.Link
func (_e *StateUpdater_Expecter) UpdateState(ctx interface{}, tgID interface{}, state interface{}, link interface{}) *StateUpdater_UpdateState_Call {
	return &StateUpdater_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, tgID, state, link)}
}

func (_c *StateUpdater_UpdateState_Call) Run(run func(ctx context.Context, tgID int64, state int, link *domain.Link)) *StateUpdater_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(*domain.Link))
	})
	return _c
}

func (_c *StateUpdater_UpdateState_Call) Return(_a0 error) *StateUpdater_UpdateState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateUpdater_UpdateState_Call) RunAndReturn(run func(context.Context, int64, int, *domain.Link) error) *StateUpdater_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateUpdater creates a new instance of StateUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateUpdater {
	mock := &StateUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
