// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	domain "LinkTracker/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function with given fields: id, link
func (_m *Database) AddLink(id int64, link domain.Link) error {
	ret := _m.Called(id, link)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, domain.Link) error); ok {
		r0 = rf(id, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type Database_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - id int64
//   - link domain.Link
func (_e *Database_Expecter) AddLink(id interface{}, link interface{}) *Database_AddLink_Call {
	return &Database_AddLink_Call{Call: _e.mock.On("AddLink", id, link)}
}

func (_c *Database_AddLink_Call) Run(run func(id int64, link domain.Link)) *Database_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(domain.Link))
	})
	return _c
}

func (_c *Database_AddLink_Call) Return(_a0 error) *Database_AddLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_AddLink_Call) RunAndReturn(run func(int64, domain.Link) error) *Database_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: id
func (_m *Database) CreateUser(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Database_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - id int64
func (_e *Database_Expecter) CreateUser(id interface{}) *Database_CreateUser_Call {
	return &Database_CreateUser_Call{Call: _e.mock.On("CreateUser", id)}
}

func (_c *Database_CreateUser_Call) Run(run func(id int64)) *Database_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Database_CreateUser_Call) Return(_a0 error) *Database_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_CreateUser_Call) RunAndReturn(run func(int64) error) *Database_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function with given fields: id, link
func (_m *Database) DeleteLink(id int64, link domain.Link) (domain.Link, error) {
	ret := _m.Called(id, link)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, domain.Link) (domain.Link, error)); ok {
		return rf(id, link)
	}
	if rf, ok := ret.Get(0).(func(int64, domain.Link) domain.Link); ok {
		r0 = rf(id, link)
	} else {
		r0 = ret.Get(0).(domain.Link)
	}

	if rf, ok := ret.Get(1).(func(int64, domain.Link) error); ok {
		r1 = rf(id, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type Database_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - id int64
//   - link domain.Link
func (_e *Database_Expecter) DeleteLink(id interface{}, link interface{}) *Database_DeleteLink_Call {
	return &Database_DeleteLink_Call{Call: _e.mock.On("DeleteLink", id, link)}
}

func (_c *Database_DeleteLink_Call) Run(run func(id int64, link domain.Link)) *Database_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(domain.Link))
	})
	return _c
}

func (_c *Database_DeleteLink_Call) Return(_a0 domain.Link, _a1 error) *Database_DeleteLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_DeleteLink_Call) RunAndReturn(run func(int64, domain.Link) (domain.Link, error)) *Database_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: id
func (_m *Database) DeleteUser(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type Database_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - id int64
func (_e *Database_Expecter) DeleteUser(id interface{}) *Database_DeleteUser_Call {
	return &Database_DeleteUser_Call{Call: _e.mock.On("DeleteUser", id)}
}

func (_c *Database_DeleteUser_Call) Run(run func(id int64)) *Database_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Database_DeleteUser_Call) Return(_a0 error) *Database_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_DeleteUser_Call) RunAndReturn(run func(int64) error) *Database_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllLinks provides a mock function with given fields:
func (_m *Database) GetAllLinks() ([]domain.Link, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllLinks")
	}

	var r0 []domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Link, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Link); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_GetAllLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllLinks'
type Database_GetAllLinks_Call struct {
	*mock.Call
}

// GetAllLinks is a helper method to define mock.On call
func (_e *Database_Expecter) GetAllLinks() *Database_GetAllLinks_Call {
	return &Database_GetAllLinks_Call{Call: _e.mock.On("GetAllLinks")}
}

func (_c *Database_GetAllLinks_Call) Run(run func()) *Database_GetAllLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_GetAllLinks_Call) Return(_a0 []domain.Link, _a1 error) *Database_GetAllLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_GetAllLinks_Call) RunAndReturn(run func() ([]domain.Link, error)) *Database_GetAllLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields:
func (_m *Database) GetAllUsers() ([]int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type Database_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
func (_e *Database_Expecter) GetAllUsers() *Database_GetAllUsers_Call {
	return &Database_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers")}
}

func (_c *Database_GetAllUsers_Call) Run(run func()) *Database_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_GetAllUsers_Call) Return(_a0 []int64, _a1 error) *Database_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_GetAllUsers_Call) RunAndReturn(run func() ([]int64, error)) *Database_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLinks provides a mock function with given fields: id
func (_m *Database) GetUserLinks(id int64) ([]domain.Link, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLinks")
	}

	var r0 []domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.Link, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.Link); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_GetUserLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLinks'
type Database_GetUserLinks_Call struct {
	*mock.Call
}

// GetUserLinks is a helper method to define mock.On call
//   - id int64
func (_e *Database_Expecter) GetUserLinks(id interface{}) *Database_GetUserLinks_Call {
	return &Database_GetUserLinks_Call{Call: _e.mock.On("GetUserLinks", id)}
}

func (_c *Database_GetUserLinks_Call) Run(run func(id int64)) *Database_GetUserLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Database_GetUserLinks_Call) Return(_a0 []domain.Link, _a1 error) *Database_GetUserLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_GetUserLinks_Call) RunAndReturn(run func(int64) ([]domain.Link, error)) *Database_GetUserLinks_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
