// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	domain "LinkTracker/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LinkRepo is an autogenerated mock type for the LinkRepo type
type LinkRepo struct {
	mock.Mock
}

type LinkRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkRepo) EXPECT() *LinkRepo_Expecter {
	return &LinkRepo_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function with given fields: ctx, tgID, link
func (_m *LinkRepo) AddLink(ctx context.Context, tgID int64, link domain.Link) error {
	ret := _m.Called(ctx, tgID, link)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Link) error); ok {
		r0 = rf(ctx, tgID, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepo_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type LinkRepo_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
//   - link domain.Link
func (_e *LinkRepo_Expecter) AddLink(ctx interface{}, tgID interface{}, link interface{}) *LinkRepo_AddLink_Call {
	return &LinkRepo_AddLink_Call{Call: _e.mock.On("AddLink", ctx, tgID, link)}
}

func (_c *LinkRepo_AddLink_Call) Run(run func(ctx context.Context, tgID int64, link domain.Link)) *LinkRepo_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Link))
	})
	return _c
}

func (_c *LinkRepo_AddLink_Call) Return(_a0 error) *LinkRepo_AddLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepo_AddLink_Call) RunAndReturn(run func(context.Context, int64, domain.Link) error) *LinkRepo_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function with given fields: ctx, tgID, link
func (_m *LinkRepo) DeleteLink(ctx context.Context, tgID int64, link domain.Link) (domain.Link, error) {
	ret := _m.Called(ctx, tgID, link)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Link) (domain.Link, error)); ok {
		return rf(ctx, tgID, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Link) domain.Link); ok {
		r0 = rf(ctx, tgID, link)
	} else {
		r0 = ret.Get(0).(domain.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.Link) error); ok {
		r1 = rf(ctx, tgID, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepo_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type LinkRepo_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
//   - link domain.Link
func (_e *LinkRepo_Expecter) DeleteLink(ctx interface{}, tgID interface{}, link interface{}) *LinkRepo_DeleteLink_Call {
	return &LinkRepo_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, tgID, link)}
}

func (_c *LinkRepo_DeleteLink_Call) Run(run func(ctx context.Context, tgID int64, link domain.Link)) *LinkRepo_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Link))
	})
	return _c
}

func (_c *LinkRepo_DeleteLink_Call) Return(_a0 domain.Link, _a1 error) *LinkRepo_DeleteLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepo_DeleteLink_Call) RunAndReturn(run func(context.Context, int64, domain.Link) (domain.Link, error)) *LinkRepo_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllLinks provides a mock function with given fields: ctx
func (_m *LinkRepo) GetAllLinks(ctx context.Context) ([]domain.Link, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllLinks")
	}

	var r0 []domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Link, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Link); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepo_GetAllLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllLinks'
type LinkRepo_GetAllLinks_Call struct {
	*mock.Call
}

// GetAllLinks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LinkRepo_Expecter) GetAllLinks(ctx interface{}) *LinkRepo_GetAllLinks_Call {
	return &LinkRepo_GetAllLinks_Call{Call: _e.mock.On("GetAllLinks", ctx)}
}

func (_c *LinkRepo_GetAllLinks_Call) Run(run func(ctx context.Context)) *LinkRepo_GetAllLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LinkRepo_GetAllLinks_Call) Return(_a0 []domain.Link, _a1 error) *LinkRepo_GetAllLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepo_GetAllLinks_Call) RunAndReturn(run func(context.Context) ([]domain.Link, error)) *LinkRepo_GetAllLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLinks provides a mock function with given fields: ctx, tgID
func (_m *LinkRepo) GetUserLinks(ctx context.Context, tgID int64) ([]domain.Link, error) {
	ret := _m.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLinks")
	}

	var r0 []domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Link, error)); ok {
		return rf(ctx, tgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Link); ok {
		r0 = rf(ctx, tgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, tgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepo_GetUserLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLinks'
type LinkRepo_GetUserLinks_Call struct {
	*mock.Call
}

// GetUserLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
func (_e *LinkRepo_Expecter) GetUserLinks(ctx interface{}, tgID interface{}) *LinkRepo_GetUserLinks_Call {
	return &LinkRepo_GetUserLinks_Call{Call: _e.mock.On("GetUserLinks", ctx, tgID)}
}

func (_c *LinkRepo_GetUserLinks_Call) Run(run func(ctx context.Context, tgID int64)) *LinkRepo_GetUserLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LinkRepo_GetUserLinks_Call) Return(_a0 []domain.Link, _a1 error) *LinkRepo_GetUserLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepo_GetUserLinks_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Link, error)) *LinkRepo_GetUserLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByLink provides a mock function with given fields: ctx, linkID
func (_m *LinkRepo) GetUsersByLink(ctx context.Context, linkID int64) ([]int64, error) {
	ret := _m.Called(ctx, linkID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByLink")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, linkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, linkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, linkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepo_GetUsersByLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByLink'
type LinkRepo_GetUsersByLink_Call struct {
	*mock.Call
}

// GetUsersByLink is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
func (_e *LinkRepo_Expecter) GetUsersByLink(ctx interface{}, linkID interface{}) *LinkRepo_GetUsersByLink_Call {
	return &LinkRepo_GetUsersByLink_Call{Call: _e.mock.On("GetUsersByLink", ctx, linkID)}
}

func (_c *LinkRepo_GetUsersByLink_Call) Run(run func(ctx context.Context, linkID int64)) *LinkRepo_GetUsersByLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LinkRepo_GetUsersByLink_Call) Return(_a0 []int64, _a1 error) *LinkRepo_GetUsersByLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepo_GetUsersByLink_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *LinkRepo_GetUsersByLink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTimeLink provides a mock function with given fields: ctx, lastUpdate, linkID
func (_m *LinkRepo) UpdateTimeLink(ctx context.Context, lastUpdate time.Time, linkID int64) error {
	ret := _m.Called(ctx, lastUpdate, linkID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTimeLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int64) error); ok {
		r0 = rf(ctx, lastUpdate, linkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepo_UpdateTimeLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTimeLink'
type LinkRepo_UpdateTimeLink_Call struct {
	*mock.Call
}

// UpdateTimeLink is a helper method to define mock.On call
//   - ctx context.Context
//   - lastUpdate time.Time
//   - linkID int64
func (_e *LinkRepo_Expecter) UpdateTimeLink(ctx interface{}, lastUpdate interface{}, linkID interface{}) *LinkRepo_UpdateTimeLink_Call {
	return &LinkRepo_UpdateTimeLink_Call{Call: _e.mock.On("UpdateTimeLink", ctx, lastUpdate, linkID)}
}

func (_c *LinkRepo_UpdateTimeLink_Call) Run(run func(ctx context.Context, lastUpdate time.Time, linkID int64)) *LinkRepo_UpdateTimeLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int64))
	})
	return _c
}

func (_c *LinkRepo_UpdateTimeLink_Call) Return(_a0 error) *LinkRepo_UpdateTimeLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepo_UpdateTimeLink_Call) RunAndReturn(run func(context.Context, time.Time, int64) error) *LinkRepo_UpdateTimeLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkRepo creates a new instance of LinkRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepo {
	mock := &LinkRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
