// Package scrapperdto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package scrapperdto

// ApiErrorResponse defines model for ApiErrorResponse.
type ApiErrorResponse struct {
	Code             *string   `json:"code,omitempty"`
	Description      *string   `json:"description,omitempty"`
	ExceptionMessage *string   `json:"exceptionMessage,omitempty"`
	ExceptionName    *string   `json:"exceptionName,omitempty"`
	Stacktrace       *[]string `json:"stacktrace,omitempty"`
}

// LinkRequest defines model for LinkRequest.
type LinkRequest struct {
	Filters *[]string `json:"filters,omitempty"`
	Link    *string   `json:"link,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// LinkResponse defines model for LinkResponse.
type LinkResponse struct {
	Filters *[]string `json:"filters,omitempty"`
	Id      *int64    `json:"id,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
	Url     *string   `json:"url,omitempty"`
}

// ListLinksResponse defines model for ListLinksResponse.
type ListLinksResponse struct {
	Links *[]LinkResponse `json:"links,omitempty"`
	Size  *int32          `json:"size,omitempty"`
}

// RemoveLinkRequest defines model for RemoveLinkRequest.
type RemoveLinkRequest struct {
	Link *string `json:"link,omitempty"`
}

// StateRequest defines model for StateRequest.
type StateRequest struct {
	Filters *[]string `json:"filters,omitempty"`
	Link    *string   `json:"link,omitempty"`
	State   *int      `json:"state,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// StateResponse defines model for StateResponse.
type StateResponse struct {
	Filters *[]string `json:"filters,omitempty"`
	Link    *string   `json:"link,omitempty"`
	State   *int      `json:"state,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// DeleteLinksParams defines parameters for DeleteLinks.
type DeleteLinksParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// GetLinksParams defines parameters for GetLinks.
type GetLinksParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// PostLinksParams defines parameters for PostLinks.
type PostLinksParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// PutLinksParams defines parameters for PutLinks.
type PutLinksParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// DeleteStatesParams defines parameters for DeleteStates.
type DeleteStatesParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// GetStatesParams defines parameters for GetStates.
type GetStatesParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// PostStatesParams defines parameters for PostStates.
type PostStatesParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// PutStatesParams defines parameters for PutStates.
type PutStatesParams struct {
	TgChatId int64 `json:"Tg-Chat-Id"`
}

// DeleteLinksJSONRequestBody defines body for DeleteLinks for application/json ContentType.
type DeleteLinksJSONRequestBody = RemoveLinkRequest

// PostLinksJSONRequestBody defines body for PostLinks for application/json ContentType.
type PostLinksJSONRequestBody = LinkRequest

// PutLinksJSONRequestBody defines body for PutLinks for application/json ContentType.
type PutLinksJSONRequestBody = LinkRequest

// PostStatesJSONRequestBody defines body for PostStates for application/json ContentType.
type PostStatesJSONRequestBody = StateRequest

// PutStatesJSONRequestBody defines body for PutStates for application/json ContentType.
type PutStatesJSONRequestBody = StateRequest
